---
- hosts: hadoop
  become: yes
  tasks:
  - name: create /opt directory
    file: path=/opt state=directory
    become: yes
  - name: Unzip hadoop from tarball
    unarchive:
      src: hadoop.tar.gz
      dest: /opt
  - name: rename hadoop-2.7.3 to hadoop
    command: mv /opt/hadoop-2.7.3 /opt/hadoop
