---
- hosts: hadoop
  remote_user: hduser
  become: true
  tasks:
  - name: Create /opt directory if it doesnt exist
    file: path=/opt state=directory

  - name: Ensure hadoop directory exists
    stat: path=/opt/hadoop
    register: p

  - name: Copy and extract hadoop-2.7.3 if hadoop is not installed
    unarchive:
      src: hadoop.tar.gz    #extract into variable
      dest: /opt
    when: not p.stat.exists

  - name: rename hadoop-2.7.3 to hadoop
    command: mv /opt/hadoop-2.7.3 /opt/hadoop
    when: not p.stat.exists
