---
- hosts: hadoop
  remote_user: hduser
  tasks:
    - name: Start Hadoop dfs -- /opt/hadoop/sbin/start-dfs.sh
      shell: /opt/hadoop/sbin/start-dfs.sh
    - name: Start Hadoop yarn -- /opt/hadoop/sbin/start-yarn.sh
      shell: /opt/hadoop/sbin/start-yarn.sh
